config/routes.rb
Rails.application.routes.draw do
  
  root 'opportunities#index'
  resources :opportunities
  resources :accounts
  resources :contacts
  
  get 'hello/index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  self.table_name = 'salesforcebearer.account'
  self.inheritance_column = nil
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  self.table_name = 'salesforcebearer.contact'
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  validates :name, presence: true
  self.table_name = 'salesforcebearer.opportunity'
end

app/models/opportunity_stage.rb
class OpportunityStage < ActiveRecord::Base
  self.table_name = 'salesforcebearer.opportunitystage'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
    @accounts = Account.all
  end
  
  def new 
  end
  
  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account
    else
      render 'new'
    end
  end
  
  def destroy
    @account = Account.find(params[:id])
    @account.destroy
 
    redirect_to accounts_path
  end
  
  def show
    @account = Account.find(params[:id])
  end
  
  def update
    @account = Account.find(params[:id])

    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit'
    end
  end
  
  def edit
    @account = Account.find(params[:id])
  end
  
  private
  def account_params
    params.require(:account).permit(:name, :type)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all
  end
  
  def new 
  end
  
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
  end
  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
 
    redirect_to contacts_path
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end
  
  def edit
    @contact = Contact.find(params[:id])
  end
  
  private
  def contact_params
    params.require(:contact).permit(:name, :type, :website, :account__bearerid__c )
  end
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  
  def index
    @opportunities = Opportunity.all
  end
  
  def new 
    @opportunity = Opportunity.new
  end
  
  def create
    @opportunity = Opportunity.new(opportunity_params)

    if @opportunity.save
      redirect_to @opportunity
    else
      render 'new'
    end
  end
  
  def destroy
    @opportunity = Opportunity.find(params[:id])
    @opportunity.destroy
 
    redirect_to opportunities_path
  end
  
  def show
    @opportunity = Opportunity.find(params[:id])
  end
  
  def update
    @opportunity = Opportunity.find(params[:id])

    if @opportunity.update(opportunity_params)
      redirect_to @opportunity
    else
      render 'edit'
    end
  end
  
  def edit
    @opportunity = Opportunity.find(params[:id])
  end
  
  private
  def opportunity_params
    params.require(:opportunity).permit(:name, :description, :amount, :closedate, :stagename)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/accounts/index.html.erb
<header>
	<h1>Lista de Cuentas</h1>
</header>
<section>
	<%= link_to 'Nueva cuenta', new_account_path %>
	
	<table class="table">
	  <tr>
	    <th>Nombre</th>
		<th>Tipo</th>
		<th width='30%'>Descripción</th>
	    <th>Ciudad</th>
		<th>País</th>
		<th>Created Date</th>
	    <th colspan="2"></th>
	  </tr>
	
	  <% @accounts.each do |account| %>
	    <tr>
	      <td><%= account.name %></td>
		  <td><%= account.type %></td>
		  <td><%= account.description %></td>
	      <td><%= account.shippingcity %></td>
	      <td><%= account.shippingcountry %></td>
	      <td><%= account.createddate %></td>
	      <td><%= link_to 'Ver', account_path(account) %></td>
	      <td><%= link_to 'Editar', edit_account_path(account) %></td>
	      <td><%= link_to 'Borrar', account_path(account),
	              method: :delete,
	              data: { confirm: '¿Seguro?' } %></td>
	    </tr>
	  <% end %>
	</table>
</section>

app/views/accounts/new.html.erb
<h1>Nueva Cuenta</h1>

<%= form_for :account, url: accounts_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :shippingcity %><br>
    <%= f.text_area :shippingcity %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/contacts/edit.html.erb
404

app/views/contacts/index.html.erb
<header>
	<h1>Lista de Contactos</h1>
</header>
<section>
	<%= link_to 'Nuevo contacto', new_contact_path %>
	
	<table class="table">
	  <tr>
		<th>Foto</th>
	    <th>Alias</th>
	    <th>Email</th>
	    <th>Nombre</th>
	    <th>Apellido</th>
	    <th>Teléfono</th>
		<th>Cuenta</th>
	    <th colspan="2"></th>
	  </tr>
	
	  <% @contacts.each do |contact| %>
	    <tr>
	      <td><%= image_tag "https://emea.salesforce.com#{contact.photourl}" %></td>
	      <td><%= contact.name %></td>
	      <td><%= contact.email %></td>
	      <td><%= contact.firstname %></td>
	      <td><%= contact.lastname %></td>
	      <td><%= contact.phone %></td>
	      <td><%= contact.account__bearerid__c %></td>
	      <td><%= link_to 'Ver', contact_path(contact) %></td>
	      <td><%= link_to 'Editar', edit_contact_path(contact) %></td>
	      <td><%= link_to 'Borrar', contact_path(contact),
	              method: :delete,
	              data: { confirm: '¿Seguro?' } %></td>
	    </tr>
	  <% end %>
	</table>
</section>

app/views/contacts/new.html.erb
<h1>Nuevo Contacto</h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :shippingcity %><br>
    <%= f.text_area :shippingcity %>
  </p>
  
  <p>
    <%= f.label 'Cuenta' %><br>
    <%= select(:contact, :account__bearerid__c, Account.all.collect { |c| [c.name,c.id] }) %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/hello/index.html.erb
<h1>Hello#index</h1>
<p>¡Hola mundo!</p>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bearer</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      	<div id="main-container" class="container">
      	  <div class="row" style='background-color: #000312;'>
        	<div class="col-xs-3">
        	  <h2 style='color:white;'>Axpe Bearer</h2>
			</div>
        	<div class="col-xs-9">
    			<form class="form-inline">
    			    <div class="form-group">
    			        <label class="sr-only" for="inputEmail">Email</label>
    			        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    			    </div>
    			    <div class="form-group">
    			        <label class="sr-only" for="inputPassword">Contraseña</label>
    			        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    			    </div>
    			    <div class="checkbox">
    			        <label><input type="checkbox"> Recordar</label>
    			    </div>
    			    <button type="submit" class="btn btn-primary">Acceder</button>
    			</form>	
			</div>
      	  </div>
		  <div class="row">
      	    <div class="col-xs-3">
	  			<header>
	  				<nav>
		        	    <h3>Índice</h3>
	  					<ul>
	  						<li><%= link_to 'Opportunities', opportunities_path %></li>
	  						<li><%= link_to 'Accounts', accounts_path %></li>
	  						<li><%= link_to 'Contacts', contacts_path %></li>
	  					</ul>
	  				</nav>
	  			</header>
      	    </div>
      	    <div class="col-xs-9">
      	      <%= yield %>
      	    </div>
      	  </div>
      	</div>
  </body>
</html>

app/views/opportunities/edit.html.erb
<h1>Editar oportunidad</h1>

<%= form_for :opportunity, url: opportunity_path(@opportunity), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :closedate %><br>
    <%= f.date_field :closedate %>
  </p>

  <p>
    <%= f.label :stagename %><br>
    <%= f.text_field :stagename %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Atrás', opportunities_path %>

app/views/opportunities/index.html.erb
<h1>Lista de oportunidades</h1>

<%= link_to new_opportunity_path, {class: "btn btn-default btn"} do %>
  <span class="glyphicon glyphicon-plus"/>Nueva Oportunidad 
<% end %>

<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Fecha de Fin</th>
    <th>Estado</th>
    <th>Administración</th>
  </tr>

  <% @opportunities.each do |opportunity| %>
    <tr>
      <td><%= opportunity.name %></td>
      <td><%= opportunity.amount %></td>
      <td><%= opportunity.closedate %></td>
      <td><%= opportunity.stagename %></td>
      <td>
		  <%= link_to opportunity_path(opportunity), {class: "btn btn-default btn-sm "} do %>
		  	<span class="glyphicon glyphicon-info-sign"/>
		  <% end %>
          <%= link_to edit_opportunity_path(opportunity), {class: "btn btn-default btn-sm "} do %>
  			<span class="glyphicon glyphicon-edit"/>
		  <% end %>
      	  <%= link_to opportunity_path(opportunity), {
		      class: "btn btn-default btn-sm ",
              method: :delete,
              data: { confirm: '¿Seguro?' } } do %>
				  <span class="glyphicon glyphicon-remove"/>
		  <% end %>
	  </td>
    </tr>
  <% end %>
</table>

app/views/opportunities/new.html.erb
<h1>Nueva Oportunidad</h1>

<%= form_for :opportunity, url: opportunities_path do |f| %>

  <% if @opportunity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@opportunity.errors.count, "error") %>
        prohibited this opportunity from being saved:
      </h2>
      <ul>
        <% @opportunity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :closedate %><br>
    <%= f.date_field :closedate %>
  </p>

  <p>
    <%= f.label :stagename %><br>
    <%= select(:opportunity, :stagename, OpportunityStage.all.collect { |os| os.masterlabel }) %>
  </p>

  <p><%= f.submit %></p>
<% end %>

<%= link_to 'Atrás', opportunities_path %>

app/views/opportunities/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @opportunity.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @opportunity.description %>
</p>

<p>
  <strong>Cantidad: </strong>
  <%= @opportunity.amount %>
</p>

<p>
  <strong>Fecha de Fin:</strong>
  <%= @opportunity.closedate %>
</p>

<p>
  <strong>StageName:</strong>
  <%= @opportunity.stagename %>
</p>

<%= link_to 'Editar', edit_opportunity_path(@opportunity) %> | 
<%= link_to 'Atrás', opportunities_path %>